name: 2023-07-24-tac-hep-tutorial
channels:
  - conda-forge
dependencies:
  - awkward
  - cxx-compiler
  - dask
  - dask-awkward
  - dask-labextension
  - distributed
  - jupyterlab
  - jupyterlab-deck
  - matplotlib
  - numba
  - numpy
  - pybind11
  - uproot
  - vector
